theme: hugo-theme-chi
themesDir: ../..
title: 痴货发明家
params:
  dateFormat: 2006-01-02
  home:
    profile:
      subtitle: 平凡而朴素的程序员
  nav:
    bilibili: https://space.bilibili.com/401571418
    github: https://github.com/langwan
markup:
  highlight:
    noClasses: false
defaultContentLanguage: zh-cn
