theme: chidocs
themesDir: ../..
baseUrl: https://langwan.github.io/chidocs/
title: ChiDocs
canonifyurls: true
params:
  dateFormat: 2006-01-02
  home:
    profile:
      subtitle: 一个简洁的 Hugo 主题
    icon: "images/logo.png"
  nav:
    bilibili: https://space.bilibili.com/401571418
    github: https://github.com/langwan/chidocs
markup:
  highlight:
    noClasses: false
    tabWidth: 4
defaultContentLanguage: zh-cn
